blogproject/blog/urls.py
# coding:utf-8
"""blogproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import url
from . import views

# 视图函数命名空间
app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    # url(r'^$', views.preview, name='preview'),
    url(r'^all_post$', views.all_post, name='all_post'),
    url(r'^about$', views.about, name='about'),
    url(r'^contact$', views.contact, name='contact'),

]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls'))
]

blogproject/blog/models.py
# coding:utf-8

from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    """Django 要求模型必须继承 models.Model 类。
	Category 只需要一个简单的分类名 name 就可以了。
	CharField 指定了分类名 name 的数据类型，CharField 是字符型，
	CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
	当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
	Django 内置的全部类型可查看文档：
	https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    # 文章标题
    title = models.CharField(max_length=150)
    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，
    # 因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    abstract = models.CharField(max_length=200, blank=True)
    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。

    # 当一个model对象的ForeignKey关联的对象被删除时，默认情况下此对象也会一起被级联删除的。
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)  # 默认情况 设置ForeignKey 为 null; 这个只有设置了null 为 True的情况才能用

    tags = models.ManyToManyField(Tag, blank=True)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

blogproject/comments/models.py
from django.db import models

# Create your models here.

blogproject/blog/views.py
# coding:utf-8
import markdown
from django.shortcuts import render, get_object_or_404

from .models import Post, Category


# Create your views here.


def index(request):
    post_list = Post.objects.all().order_by('-created_time')[:4]
    return render(request, 'blog/index.html', context={'post_list': post_list})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    post.body = markdown.markdown(post.body, extensions=['markdown.extensions.extra',
                                                         'markdown.extensions.codehilite',
                                                         'markdown.extensions.toc'])
    return render(request, 'blog/detail.html', context={'post': post})


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month).order_by('-created_time')
    return render(request, 'blog/post_list.html', context={'post_list': post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/post_list.html', context={'post_list': post_list})


def all_post(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/post_list.html', context={'post_list': post_list})


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    return render(request, 'blog/contact.html')

blogproject/comments/views.py
from django.shortcuts import render

# Create your views here.

blogproject/templates/blog/about.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>黄万军的个人博客</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blog/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional fonts for this theme -->
    <link href="{% static 'blog/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this theme -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Temporary navbar container fix until Bootstrap 4 is patched -->
    <style>
    .navbar-toggler {
        z-index: 1;
    }
    
    @media (max-width: 576px) {
        nav > .container {
            width: 100%;
        }
    }
    </style>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-toggleable-md navbar-light" id="mainNav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="{% url 'blog:index' %}">黄万军的个人博客</a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:index' %}">主页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:about' %}">关于我</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:all_post' %}">文章列表</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:contact' %}">联系我</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <header class="intro-header" style="background-image: url('/static/blog/img/about-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                <p>
                    计算机在读研究生，小菜鸟一枚，欢迎大家指教！！！
                </p>
            </div>
        </div>
    </div>

    <hr>


    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/7Niwu3Vs1v9Fmt8">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://weibo.com/5283319958/profile?topnav=1&wvr=6">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/haungwanjun">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; 黄万军 </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery Version 3.1.1 -->
    <script src="{% static 'blog/lib/jquery/jquery.js' %}"></script>

    <!-- Tether -->
    <script src="{% static 'blog/lib/tether/tether.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'blog/lib/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blogproject/templates/blog/detail.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blog/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional fonts for this theme -->
    <link href="{% static 'blog/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this theme -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Temporary navbar container fix until Bootstrap 4 is patched -->
    <style>
    .navbar-toggler {
        z-index: 1;
    }
    
    @media (max-width: 576px) {
        nav > .container {
            width: 100%;
        }
    }
    </style>

</head>

<body>

      <!-- Navigation -->
    <nav class="navbar fixed-top navbar-toggleable-md navbar-light" id="mainNav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="{% url 'blog:index' %}">黄万军的个人博客</a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:index' %}">主页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:about' %}">关于我</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:all_post' %}">文章列表</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:contact' %}">联系我</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <header class="intro-header" style="background-image: url('/static/blog/img/post-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <div class="post-heading">
                       <h1>永远在路上</h1>
                        <h2 class="subheading">每天，遇见更好的自己</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <article class="post post-{{ post.pk }}">
                        <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category_name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <!--<span class="comments-link"><a href="#">4 评论</a></span>-->
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                        </header>
                        <div class="entry-content clearfix">
                            {{ post.body|safe }}
                        </div>
                    </article>
                    <div class="return_top cl-effect-14" align="center">
                        <a href="{{ post.get_absolute_url }}" class="more-link">返回顶部 <span class="meta-nav">→</span></a>
                    </div>


                </div>
                <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                        {% get_recent_posts as recent_post_list %}
                    <ul>
                    {% for post in recent_post_list %}
                        <li>
                         <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                    {% empty %}
                    暂无文章！
                    {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}
                                    年 {{ date.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span
                                        class="post-count">({{ category.num_posts }})</span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

            </aside>
            </div>
        </div>
    </article>

    <hr>


    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/7Niwu3Vs1v9Fmt8">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://weibo.com/5283319958/profile?topnav=1&wvr=6">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/haungwanjun">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; 黄万军 </p>
                </div>
            </div>
        </div>
    </footer>


    <!-- jQuery Version 3.1.1 -->
    <script src="{% static 'blog/lib/jquery/jquery.js' %}"></script>

    <!-- Tether -->
    <script src="{% static 'blog/lib/tether/tether.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'blog/lib/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blogproject/templates/blog/index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="黄万军的个人博客">
    <meta name="author" content="黄万军">

    <title>计算机小菜鸟 | 黄万军的个人博客</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blog/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional fonts for this theme -->
    <link href="{% static 'blog/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this theme -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Temporary navbar container fix until Bootstrap 4 is patched -->
    <style>
    .navbar-toggler {
        z-index: 1;
    }
    
    @media (max-width: 576px) {
        nav > .container {
            width: 100%;
        }
    }
    </style>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-toggleable-md navbar-light" id="mainNav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="{% url 'blog:index' %}">黄万军的个人博客</a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                       <a class="nav-link page-scroll" href="{% url 'blog:index' %}">主页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:about' %}">关于我</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:all_post' %}">文章列表</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'blog:contact' %}">联系我</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <header class="intro-header" style="background-image: url('/static/blog/img/index-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <div class="site-heading">
                        <h1>永远在路上</h1>
                        <span class="subheading">人生不止眼前的苟且，还有诗和远方</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="post_list">
                {% for post in post_list %}
                <article class="post post-{{ post.pk}}">
                    <header class="entry-header">
                        <h1 class="post-title" align="center">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <hr>
                        <div class="entry-meta" align="center">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <!--<span class="comments-link"><a href="#"> 评论</a></span>-->
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="post-subtitle ">
                        <p>{{ post.abstract }}</p>
                        <div class="read-more cl-effect-14" align="right">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                        <hr>
                        <hr>
                    </div>
                </article>
                {% empty %}
                <div class="no-post">暂时没有文章发布</div>
                {% endfor %}
                    <hr>
                <hr>
                    <div class="clearfix"  align="center">
                    <a class="btn btn-secondary " href="{% url 'blog:all_post' %}">全部文章 &rarr;</a>
                    </div>
                    <hr>
                </div>

            </div>


            <div class="col-md-4">
            <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                        {% get_recent_posts as recent_post_list %}
                    <ul>
                    {% for post in recent_post_list %}
                        <li>
                         <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                    {% empty %}
                    暂无文章！
                    {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}
                                    年 {{ date.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span
                                        class="post-count">({{ category.num_posts }})</span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>


            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/7Niwu3Vs1v9Fmt8">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://weibo.com/5283319958/profile?topnav=1&wvr=6">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/haungwanjun">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; 黄万军 </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery Version 3.1.1 -->
    <script src="{% static 'blog/lib/jquery/jquery.js' %}"></script>

    <!-- Tether -->
    <script src="{% static 'blog/lib/tether/tether.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'blog/lib/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blogproject/templates/blog/pagination.html
<div id="pagenavi" class="noselect" align="center" >
    {% if post_list.has_previous %}
    <!--# 判断是否还有上一页，有的话要显示一个上一页按钮-->
    <a class="previous-page" href="?page={{ post_list.previous_page_number }}">
        <span class="icon-previous"></span>上一页
    </a>
    {% endif %}

    <!--# 页码号为1永远显示-->
    {% if first_page == current_page %}
    <!--# 当前页就是第一页-->
    <span class="first-page current">1</span>
    {% else %}
    <!--# 否则的话，第一页是可以点击的，点击后通过?page=1的形式把页码号传递给视图函数-->
    <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
    <!--# 2以前的页码号要被显示成省略号了-->
    <span>...</span>
    {% endif %}

    {% for page in pages %}
    <!--# 通过for循环把pages中的值显示出来-->
    {% if page == current_page %}
    <!--# 是否当前页，按钮会显示不同的样式-->
    <span class="current">{{ page }}</span>
    {% else %}
    <a href="?page={{ page }}">{{ page }}</a>
    {% endif %}
    {% endfor %}

    <!--# pages最后一个值+1的值小于最大页码号，说明有页码号需要被省略号替换-->
    {% if pages_last < last_page %}
    <span>...</span>
    {% endif %}

    <!--# 永远显示最后一页的页码号，如果只有一页则前面已经显示了1就不用再显示了-->
    {% if last_page != 1 %}
    {% if last_page == current_page %}
    <span class="current">{{ last_page }}</span>
    {% else %}
    <a href="?page={{ last_page }}">{{ last_page }}</a>
    {% endif %}
    {% endif %}

    <!--# 还有下一页，则显示一个下一页按钮-->
    {% if post_list.has_next %}
    <a class="next-page" href="?page={{ post_list.next_page_number }}">
        下一页<span class="icon-next"></span>
    </a>
    {% endif %}
</div>